services:
    millwright.form.help_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\HelpFormTypeExtension
           tags:
                - { name: form.type_extension, alias: form } 

    millwright.form.label_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\LabelFormTypeExtension
           tags:
                - { name: form.type_extension, alias: form } 

    millwright.form.legend_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\LegendFormTypeExtension
           arguments:
                - { render_fieldset: %millwright.form.render_fieldset%, show_legend: %millwright.form.show_legend%, show_child_legend: %millwright.form.show_child_legend% }
           tags:
                - { name: form.type_extension, alias: form } 

    millwright.form.error_type_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\ErrorTypeFormTypeExtension
           arguments:
                - { error_type: %millwright.form.error_type% }
           tags:
                - { name: form.type_extension, alias: form } 

    millwright.form.widget_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\WidgetFormTypeExtension
           tags:
                - { name: form.type_extension, alias: form } 

    millwright.form.widget_collection_extension:
           class: Millwright\TwitterBootstrapBundle\Form\Extension\WidgetCollectionFormTypeExtension
           tags:
                - { name: form.type_extension, alias: form } 

