services:
    millwright_bootstrap.menu_options:
        class: "%millwright_menu.options.class%"
        tags:
            - {name: millwright_menu.menu_options}
        arguments:
            -
                renderers:
                    navigation: #menu type id
                        renderer: null
                    breadcrumbs:
                        renderer: millwright_renderer
                        rendererOptions: { block: 'breadcrumb'}
                    link:
                        renderer: millwright_renderer
                        rendererOptions: { block: 'link'}
                    actions:
                        renderer: millwright_renderer
                    dropdown:
                        rendererOptions:
                            rootClass: 'dropdown-menu'
                            currentClass: 'active'

                    pills:
                        rendererOptions:
                            rootClass: 'nav-pills'
                            currentClass: 'active'

                    tabs:
                        rendererOptions:
                            rootClass: 'nav-tabs'
                            currentClass: 'active'

                    list:
                        rendererOptions:
                            rootClass: 'nav-list'
                            currentClass: 'active'

                    stacked_pills:
                        rendererOptions:
                            rootClass: 'nav-pills nav-stacked'
                            currentClass: 'active'

                    stacked_tabs:
                        rendererOptions:
                            rootClass: 'nav-tabs nav-stacked'
                            currentClass: 'active'

                    stacked_list:
                        rendererOptions:
                            rootClass: 'nav-list nav-stacked'
                            currentClass: 'active'

                    navigation:
                        rendererOptions:
                            currentClass: 'active'

                items:
                    fos_user_registration_register:
                        translateDomain: 'MillwrightMenuBundle'
                        roles: ROLE_USER

                    fos_user_profile_show:
                        translateDomain: 'MillwrightMenuBundle'
                        showNonAuthorized: true #show link in menu for non-authorized user
                        roles: ROLE_USER

                    fos_user_change_password:
                        translateDomain: 'FOSUserBundle'
                        roles: ROLE_USER
                        label: 'change_password.submit'
